language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler:
      - gcc
    - os: linux
      dist: bionic
      compiler:
      - clang
    - os: windows
  allow_failures:
    - os: windows

script:
  - build.sh
