language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler:
      - gcc
    - os: linux
      dist: bionic
      compiler:
      - clang
      script: bash ./build.sh
    - os: windows
  allow_failures:
    - os: windows

